### ISSUE TITLE
How do I build this project?

### ISSUE THREAD

**Issue by JBHarris** [georgeOsdDev/react-draggable-tab#86]
I'm trying to make the appropriate changes to the library to allow disabling dragging on a specific component, but I'm having trouble compiling the ES6 to ES5. I installed Babel 5.8.38, then ran `babel src --out-dir lib` but I get:
``` 
C:\Projects\axiom-pro-3.0\Source\ServiceLayer\jspm_packages\github\JBHarris\react-draggable-tab@0.8.1>babel src --out-dir lib
ReferenceError: [BABEL] src\components\CloseIcon.js: Unknown option: C:\Projects\axiom-pro-3.0\Source\ServiceLayer\jspm_packages\github\JBHarris\react-draggable-tab@0.8.1\.babelrc.presets
    at Logger.error (C:\Users\james\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\transformation\file\logger.js:58:11)
    at OptionManager.mergeOptions (C:\Users\james\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:126:29)
    at OptionManager.addConfig (C:\Users\james\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:107:10)
    at OptionManager.findConfigs (C:\Users\james\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:168:35)
    at OptionManager.init (C:\Users\james\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (C:\Users\james\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (C:\Users\james\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (C:\Users\james\AppData\Roaming\npm\node_modules\babel\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at Object.exports.transform (C:\Users\james\AppData\Roaming\npm\node_modules\babel\lib\babel\util.js:40:22)
    at Object.exports.compile (C:\Users\james\AppData\Roaming\npm\node_modules\babel\lib\babel\util.js:49:20)
```

Any help you can offer is appreciated.

Thanks,
Brad

**Comment by georgeOsdDev** [comment]
I'm using babel 6.11
https://github.com/georgeOsdDev/react-draggable-tab/blob/master/package.json#L32

Please try `npm install` and `npm run build`

**Comment by JBHarris** [comment]
excellent - thanks for the pointer.
